version: '3'

services: 
  apache:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    container_name: sample_apache